### ISSUE TITLE
Failed to load the HyperlinkHelper package

### ISSUE THREAD

**Issue by anjar18** [robnyman/hyperlink-helper-atom#2]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.1.0
**System**: Microsoft Windows 7 Ultimate 
**Thrown From**: [HyperlinkHelper](https://github.com/robnyman/hyperlink-helper-atom) package, v0.2.0
### Stack Trace

Failed to load the HyperlinkHelper package

```
At Cannot read property 'prototype' of undefined

TypeError: Cannot read property 'prototype' of undefined
    at __extends (C:\Users\anjar\.atom\packages\hyperlinkhelper\lib\hyperlink-helper-view.coffee:1:1)
    at C:\Users\anjar\.atom\packages\hyperlinkhelper\lib\hyperlink-helper-view.coffee:5:3
    at Object.<anonymous> (C:\Users\anjar\.atom\packages\hyperlinkhelper\lib\hyperlink-helper-view.coffee:5:3)
    at Object.<anonymous> (C:\Users\anjar\.atom\packages\hyperlinkhelper\lib\hyperlink-helper-view.coffee:1:1)
    at Module._compile (module.js:428:26)
    at Object.defineProperty.value [as .coffee] (C:\Users\anjar\AppData\Local\atom\app-1.1.0\resources\app.asar\src\compile-cache.js:169:21)
    at Module.load (module.js:353:32)
    at Function.Module._load (module.js:308:12)
    at Module.require (module.js:363:17)
    at require (module.js:382:17)
```
### Commands

```
```
### Config

``` json
{
  "core": {
    "excludeVcsIgnoredPaths": false,
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
atom-beautify, vundefined
color-picker, v2.0.13
font-awesome-snippetset, v0.0.6
HyperlinkHelper, v0.2.0
linter, v1.8.1
pigments, v0.15.0

# Dev
No dev packages
```

**Comment by robnyman** [comment]
Sorry to hear that. Created this as a one-off, and seems like late Atom updates would break that functionality. :-/

**Comment by anjar18** [comment]
Kumaha atuh om ?

( How to clear this Problem ? )

**Comment by robnyman** [comment]
I don't know, unfortunately. If you know how to solve it, please submit a pull request here.
